### ISSUE TITLE
Valid repo, failing...

### ISSUE THREAD

**Issue by kitplummer** [gtri/lowendinsight#105]
```2021-05-24T20:42:07.838648+00:00 app[web.1]: 20:42:07.838 [info]  Cloned -> : https://github.com/rapid7/metasploit-framework
2021-05-24T20:42:11.238592+00:00 app[web.1]:
2021-05-24T20:42:11.238600+00:00 app[web.1]: 20:42:11.238 [error] Task #PID<0.2307.0> started from #PID<0.2305.0> terminating
2021-05-24T20:42:11.238601+00:00 app[web.1]: ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream, Timex.Interval
2021-05-24T20:42:11.238601+00:00 app[web.1]: (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
2021-05-24T20:42:11.238602+00:00 app[web.1]: (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:193: Enumerable.slice/1
2021-05-24T20:42:11.238602+00:00 app[web.1]: (elixir) lib/enum.ex:2835: Enum.backwards_compatible_slice/1
2021-05-24T20:42:11.238603+00:00 app[web.1]: (elixir) lib/enum.ex:3039: Enum.slice_any/3
2021-05-24T20:42:11.238603+00:00 app[web.1]: (elixir) lib/enum.ex:377: Enum.at/3
2021-05-24T20:42:11.238603+00:00 app[web.1]: (lowendinsight) lib/git_helper.ex:129: GitHelper.parse_header/1
2021-05-24T20:42:11.238604+00:00 app[web.1]: (lowendinsight) lib/git_helper.ex:99: anonymous fn/1 in GitHelper.parse_shortlog/1
2021-05-24T20:42:11.238605+00:00 app[web.1]: (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
2021-05-24T20:42:11.238605+00:00 app[web.1]: Function: &LowendinsightGet.Analysis.analyze/3
2021-05-24T20:42:11.238605+00:00 app[web.1]: Args: ["https://github.com/rapid7/metasploit-framework", "lei-get", %{types: false}]
2021-05-24T20:42:11.248961+00:00 app[web.1]:
2021-05-24T20:42:11.248961+00:00 app[web.1]: 20:42:11.248 [error] GenServer #PID<0.2308.0> terminating
2021-05-24T20:42:11.248962+00:00 app[web.1]: ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream, Timex.Interval
2021-05-24T20:42:11.248962+00:00 app[web.1]: (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
2021-05-24T20:42:11.248962+00:00 app[web.1]: (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:193: Enumerable.slice/1
2021-05-24T20:42:11.248963+00:00 app[web.1]: (elixir) lib/enum.ex:2835: Enum.backwards_compatible_slice/1
2021-05-24T20:42:11.248963+00:00 app[web.1]: (elixir) lib/enum.ex:3039: Enum.slice_any/3
2021-05-24T20:42:11.248963+00:00 app[web.1]: (elixir) lib/enum.ex:377: Enum.at/3
2021-05-24T20:42:11.248963+00:00 app[web.1]: (lowendinsight) lib/git_helper.ex:129: GitHelper.parse_header/1
2021-05-24T20:42:11.248964+00:00 app[web.1]: (lowendinsight) lib/git_helper.ex:99: anonymous fn/1 in GitHelper.parse_shortlog/1
2021-05-24T20:42:11.248964+00:00 app[web.1]: (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
2021-05-24T20:42:11.248966+00:00 app[web.1]: Last message: {:EXIT, #PID<0.2307.0>, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: '/home/build/elixir/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: '/home/build/elixir/lib/elixir/lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2835]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3039]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 377]}, {GitHelper, :parse_header, 1, [file: 'lib/git_helper.ex', line: 129]}, {GitHelper, :"-parse_shortlog/1-fun-0-", 1, [file: 'lib/git_helper.ex', line: 99]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}]}}
2021-05-24T20:42:11.248967+00:00 app[web.1]: State: #MapSet<[]>
```

As seen from the trending app.  Locally I get the following:

```
{"state":"complete","report":{"uuid":"3d73eb48-bcd5-11eb-83d8-88e9fe666193","repos":[{"header":{"uuid":"3bf7627c-bcd5-11eb-9ab5-88e9fe666193","start_time":"2021-05-24T21:14:55.441973Z","source_client":"mix task","repo":"https://github.com/rapid7/metasploit-framework","library_version":"","end_time":"2021-05-24T21:15:58.505198Z","duration":63},"data":{"risk":"undetermined","repo_size":"undetermined","repo":"https://github.com/rapid7/metasploit-framework","project_types":{"undetermined":"undetermined"},"git":{},"error":"Unable to analyze the repo (https://github.com/rapid7/metasploit-framework), is this a valid Git repo URL?"}}]},"metadata":{"times":{"start_time":"2021-05-24T21:14:55.437016Z","end_time":"2021-05-24T21:16:00.999519Z","duration":65},"risk_counts":{"undetermined":1},"repo_count":1}}
```

with no stacktrace errors.

**Comment by kitplummer** [comment]
```
CONTRIB:: "Che5hireC4t <á.Fx±¸8ø4zjQ$ï'\\_KÚ(Ä×¼êf;?ò¾,i«·EÔ©K©¥uè8GkÑ./òÙ)96^¾'ñ´Ä'qT#> (2):\n      Adding a documentation file.\n      Adding metadata to ruby module."
```

'Tis the culprit in that repo.
