### ISSUE TITLE
GitModule.get_diff_2_commits error.

### ISSUE THREAD

**Issue by kitplummer** [gtri/lowendinsight#28]
```
16:54:43.262 [info]  Analyzing https://github.com/shadowsocks/shadowsocks

16:54:44.002 [error] Task #PID<0.92.0> started from #PID<0.377.0> terminating
** (FunctionClauseError) no function clause matching in GitModule.get_diff_2_commits/2
    lib/git_module.ex:119: GitModule.get_diff_2_commits(%Git.Repository{path: "/home/cplummer8/lei-1584737683-7173-22wuw3/shadowsocks"}, ["938bba3"])
    lib/git_module.ex:152: GitModule.get_last_2_delta/1
    lib/git_module.ex:141: GitModule.get_recent_changes/1
    lib/analyzer_module.ex:66: AnalyzerModule.analyze/2
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &AnalyzerModule.analyze/2
    Args: ["https://github.com/shadowsocks/shadowsocks", "mix task"]
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in GitModule.get_diff_2_commits/2
        lib/git_module.ex:119: GitModule.get_diff_2_commits(%Git.Repository{path: "/home/cplummer8/lei-1584737683-7173-22wuw3/shadowsocks"}, ["938bba3"])
        lib/git_module.ex:152: GitModule.get_last_2_delta/1
        lib/git_module.ex:141: GitModule.get_recent_changes/1
        lib/analyzer_module.ex:66: AnalyzerModule.analyze/2
        (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by kitplummer** [comment]
Looks like there is only 1 commit.  :D
