### ISSUE TITLE
Crash during top-1k run

### ISSUE THREAD

**Issue by kitplummer** [gtri/lowendinsight#35]
```
13:56:56.277 [error] Task #PID<0.92.0> started from #PID<0.1568.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    lib/git_helper.ex:139: anonymous fn/1 in GitHelper.get_contributor_counts/2
    (elixir 1.10.2) lib/map.ex:837: Map.get_and_update/3
    lib/git_helper.ex:138: GitHelper.get_contributor_counts/2
    lib/git_module.ex:191: GitModule.get_contributor_distribution/1
    lib/git_module.ex:197: GitModule.get_functional_contributors/1
    lib/analyzer_module.ex:73: AnalyzerModule.analyze/2
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: &AnalyzerModule.analyze/2
    Args: ["https://github.com/odoo/odoo", "mix task"]
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        lib/git_helper.ex:139: anonymous fn/1 in GitHelper.get_contributor_counts/2
        (elixir 1.10.2) lib/map.ex:837: Map.get_and_update/3
        lib/git_helper.ex:138: GitHelper.get_contributor_counts/2
        lib/git_module.ex:191: GitModule.get_contributor_distribution/1
        lib/git_module.ex:197: GitModule.get_functional_contributors/1
        lib/analyzer_module.ex:73: AnalyzerModule.analyze/2
        (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
```

**Comment by kitplummer** [comment]
Replicated directly: 

```
[cplummer8@ice154 lowendinsight]$ mix lei.analyze https://github.com/odoo/odoo

14:05:14.416 [info]  Cloned -> https://github.com/odoo/odoo

14:05:27.317 [error] Task #PID<0.92.0> started from #PID<0.185.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    lib/git_helper.ex:139: anonymous fn/1 in GitHelper.get_contributor_counts/2
    (elixir 1.10.2) lib/map.ex:837: Map.get_and_update/3
    lib/git_helper.ex:138: GitHelper.get_contributor_counts/2
    lib/git_module.ex:191: GitModule.get_contributor_distribution/1
    lib/git_module.ex:197: GitModule.get_functional_contributors/1
    lib/analyzer_module.ex:73: AnalyzerModule.analyze/2
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: &AnalyzerModule.analyze/2
    Args: ["https://github.com/odoo/odoo", "mix task"]
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        lib/git_helper.ex:139: anonymous fn/1 in GitHelper.get_contributor_counts/2
        (elixir 1.10.2) lib/map.ex:837: Map.get_and_update/3
        lib/git_helper.ex:138: GitHelper.get_contributor_counts/2
        lib/git_module.ex:191: GitModule.get_contributor_distribution/1
        lib/git_module.ex:197: GitModule.get_functional_contributors/1
        lib/analyzer_module.ex:73: AnalyzerModule.analyze/2
        (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
```

**Comment by kitplummer** [comment]
Fixed.  This repo was just huge.  Issue was with how it was was getting run.
