### ISSUE TITLE
Temp cleanup happening before all analysis is complete...

### ISSUE THREAD

**Issue by kitplummer** [gtri/lowendinsight#36]
I think.

```

22:06:35.683 [info]  Cloned -> https://github.com/carbon-app/carbon

22:06:37.574 [error] Task #PID<0.92.0> started from #PID<0.823.0> terminating
** (stop) exited in: :gen_server.call(:file_server_2, {:list_dir, '/home/cplummer8/tmp/lei-1585188361-11710-jzk4pe/localstack/tests/integration/test_kms.py'})
    ** (EXIT) time out
    (stdlib 3.11) gen_server.erl:215: :gen_server.call/2
    (elixir 1.10.2) lib/path.ex:596: Path.Wildcard.list_dir/1
    (stdlib 3.11) filelib.erl:293: :filelib.do_wildcard_3/4
    (stdlib 3.11) filelib.erl:355: :filelib.do_double_star/6
    (stdlib 3.11) filelib.erl:350: :filelib.do_double_star/6
    (stdlib 3.11) filelib.erl:278: :filelib.do_wildcard_2/4
    (stdlib 3.11) filelib.erl:260: :filelib.do_wildcard/3
    (stdlib 3.11) filelib.erl:62: :filelib.wildcard/2
Function: &AnalyzerModule.analyze/2
    Args: ["https://github.com/localstack/localstack", "mix task"]

22:06:37.574 [error] Task #PID<0.92.0> started from #PID<0.221.0> terminating
** (stop) exited in: :gen_server.call(:file_server_2, {:list_dir, '/home/cplummer8/tmp/lei-1585186487-11710-g92wr2/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1/fake/fake_namespace.go'})
    ** (EXIT) time out
    (stdlib 3.11) gen_server.erl:215: :gen_server.call/2
    (elixir 1.10.2) lib/path.ex:596: Path.Wildcard.list_dir/1
    (stdlib 3.11) filelib.erl:348: :filelib.do_double_star/6
    (stdlib 3.11) filelib.erl:350: :filelib.do_double_star/6
    (stdlib 3.11) filelib.erl:278: :filelib.do_wildcard_2/4
    (stdlib 3.11) filelib.erl:260: :filelib.do_wildcard/3
    (stdlib 3.11) filelib.erl:62: :filelib.wildcard/2
    (elixir 1.10.2) lib/path.ex:663: Path.wildcard/2
Function: &AnalyzerModule.analyze/2
    Args: ["https://github.com/kubernetes/kubernetes", "mix task"]
```

**Comment by kitplummer** [comment]
Have debugged this a bit.  Don't believe it was the temp file thing actually, more about open files.  I had been use 4 jobs per core at a time.  I think this creates too many connections/burden on IO.  Switched back to 2, and it runs smooth.  Keeping open for now.
