### ISSUE TITLE
git_helper parse_header error handling

### ISSUE THREAD

**Issue by jronmi** [gtri/lowendinsight#91]
Currently the parse header function in the git helper module is susceptible to improper information being stored in the repo it is analyzing. So far only errors in the email field have been found to throw errors, but more revision is needed to determine all vulnerabilities.

**Comment by jronmi** [comment]
https://github.com/choongsoo/chobo, input to parse_header: "choongsoo <4Lj9*6.c;Jf]oxmf2@2qKR]2> (15) ..."
 
** (Protocol.UndefinedError) an exception was raised:
     (elixir 1.10.2) lib/enum.ex:1: Enumerable.impl_for!/1
     (elixir 1.10.2) lib/enum.ex:193: Enumerable.slice/1
     (elixir 1.10.2) lib/enum.ex:3443: Enum.slice_any/3
     (elixir 1.10.2) lib/enum.ex:398: Enum.at/3
     lib/git_helper.ex:129: GitHelper.parse_header/1
     lib/git_helper.ex:99: anonymous fn/1 in GitHelper.parse_shortlog/1 ...

**Comment by jronmi** [comment]
The error is caused when regex.scan() cannot find a match and returns :nil. The current fix writes "Could not process" for all attributes; however, after some more testing we will change it so that the count variable is still used (since count is not a user input value it is much less likely to have an error). This will allow the program to continue analysis.
